name: run_echidna
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - scanpy>=1.10
  - python-igraph
  - leidenalg
  - pyro-ppl>=1.9.1
  - pandas
  - seaborn
  - hmmlearn
  - scikit-learn
  - pip
  - pip:
      - sc-echidna>=1.0.3
      - PhenoGraph
      - graphviz
